const standardProcess = [
  "Conflict check and a focused intake covering parties, facts, stage and next deadline.",
  "Assessment of limitation, jurisdiction, maintainability, evidence and available relief.",
  "A proportionate strategy for advice, notice, negotiation, filing or immediate protection.",
  "Documented next steps, drafting and updates as the matter progresses.",
];

export const PRACTICE_PAGES = {
  civil: {
    path: "/civil-litigation",
    shortTitle: "Civil litigation",
    eyebrow: "Civil disputes and court procedure",
    title: "Civil litigation in Maharashtra",
    description: "Civil litigation information for property, tenancy, contract, recovery, injunction, appeal and execution matters in Maharashtra.",
    intro: [
      "Civil disputes are shaped as much by limitation, jurisdiction, documents and interim protection as by the final legal claim. Early work should identify the correct parties, forum, relief, chronology and evidence before positions harden or records become difficult to obtain.",
      "Assistance may cover pre-litigation assessment, notices, pleadings, interim applications, evidence, arguments, appeals and enforcement. The appropriate sequence depends on the facts and the procedural stage.",
    ],
    services: [
      { title: "Early case assessment", text: "Review facts, limitation, jurisdiction, parties, cause of action, available remedies and whether urgent preservation or interim relief should be considered." },
      { title: "Pleadings and interim relief", text: "Prepare or review plaints, written statements, applications, affidavits, document lists and requests for injunction, attachment or other appropriate protection." },
      { title: "Evidence, trial and hearings", text: "Organise proof around disputed issues, admissions, witness requirements, electronic records and the procedural directions of the court." },
      { title: "Appeal, revision and execution", text: "Assess appealability, limitation, substantial questions, revisional scope, stay requirements and practical enforcement of decrees or orders." },
    ],
    matters: ["Property, possession, tenancy and access disputes", "Contracts, recovery, damages and specific performance", "Temporary and permanent injunctions", "Partnership, commercial and account disputes", "Civil appeals, revisions, writ-related assessment and second appeals", "Execution, attachment and enforcement-related applications"],
    documents: ["A dated chronology and list of all parties", "Contracts, title documents, notices and material correspondence", "Payment records, account statements and acknowledgements", "Earlier pleadings, orders, court notices and case numbers", "Photographs, maps, public records or electronic evidence", "The next hearing, filing or limitation date"],
    process: standardProcess,
    scopeNote: "No civil remedy or interim order is automatic. Courts consider pleadings, proof, conduct, delay, balance of convenience, statutory limits and other factors. A website summary cannot determine limitation or the correct forum for a particular dispute.",
    faqs: [
      { question: "What should I bring to a first civil consultation?", answer: "Bring a short chronology, the most important agreements or title records, notices, payment proof, any existing pleadings or orders and the next known deadline. Start with an index rather than an unorganised document dump." },
      { question: "Can urgent interim relief be requested?", answer: "It may be considered where facts and law support it, but urgency alone is not sufficient. The court will assess the legal right, prima facie case, comparative harm, delay, conduct and the form of relief sought." },
      { question: "Do you appear before the Bombay High Court?", answer: "Appearances include matters before the Bombay High Court as well as District Courts and tribunals, subject to the nature, stage and forum of the particular matter." },
    ],
  },
  criminal: {
    path: "/criminal-bail",
    shortTitle: "Criminal matters & bail",
    eyebrow: "BNS, BNSS and BSA procedure",
    title: "Criminal matters and bail",
    description: "Criminal matter information for anticipatory bail, regular bail, quashing, revisions and trial preparation under the BNS, BNSS and BSA.",
    intro: [
      "Criminal matters require immediate attention to the alleged offence, procedural stage, custody risk, evidence, jurisdiction and the next operational deadline. The Bharatiya Nyaya Sanhita, 2023, Bharatiya Nagarik Suraksha Sanhita, 2023 and Bharatiya Sakshya Adhiniyam, 2023 must be distinguished and applied to the relevant facts and transition position.",
      "Assistance may involve bail strategy, document preparation, procedural applications, revisions, quashing assessment and trial work. No bail or quashing outcome can be predicted from a short account alone.",
    ],
    services: [
      { title: "Anticipatory bail", text: "Assess the accusation, non-bailable offences, apprehension of arrest, forum, chronology, cooperation, antecedents and supporting material for an application under the applicable procedure." },
      { title: "Regular bail and custody-stage work", text: "Review arrest and remand records, alleged role, investigation status, statutory factors, conditions and the material needed for a focused bail request." },
      { title: "Revision and quashing assessment", text: "Examine maintainability, alternative remedies, procedural history, allegations, undisputed documents and the limited nature of supervisory or inherent jurisdiction." },
      { title: "Trial and evidence preparation", text: "Organise the charge, prosecution material, defence documents, witness issues and electronic evidence within the BNS, BNSS and BSA framework." },
    ],
    matters: ["Anticipatory bail under section 482 BNSS", "Regular bail and bail conditions", "Remand, investigation-stage and procedural applications", "Criminal revisions and quashing petitions", "Complaint cases, summons and trial preparation", "Electronic and documentary evidence issues"],
    documents: ["FIR or complaint details and police-station information", "A precise chronology and your alleged role", "Notices, summons, remand papers and existing orders", "Supporting documents and material communications", "Accurate antecedent and prior-case information", "Immediate dates, custody status and contact details"],
    process: standardProcess,
    scopeNote: "Bail and other criminal remedies are judicial decisions based on the accusation, statutory restrictions, investigation, conduct and case-specific factors. Do not conceal prior cases, notices, warrants or material facts. If arrest or immediate safety is a concern, use an appropriate emergency channel rather than relying only on a website form.",
    sources: [{ label: "Ministry of Home Affairs: official texts of the three new criminal laws", href: "https://www.mha.gov.in/en/commoncontent/new-criminal-laws" }],
    faqs: [
      { question: "What is the current anticipatory-bail provision under BNSS?", answer: "Section 482 of the BNSS concerns a direction for grant of bail to a person apprehending arrest. The applicable offences, restrictions, forum and facts still require individual assessment." },
      { question: "What information is important for a bail consultation?", answer: "The FIR or complaint, alleged offences, police station, apprehension or custody status, dates, your alleged role, supporting documents, prior cases and the next known procedural step are usually important." },
      { question: "Are BNS, BNSS and BSA the same law?", answer: "No. Broadly, BNS addresses substantive offences, BNSS criminal procedure and BSA evidence. The correct provisions and commencement or transition position must be checked for the matter." },
    ],
  },
  rera: {
    path: "/rera-real-estate",
    shortTitle: "RERA & real estate",
    eyebrow: "Maharashtra property and project work",
    title: "MAHARERA and real-estate matters",
    description: "MAHARERA, development agreement, property due-diligence, municipal and project documentation information for Maharashtra.",
    intro: [
      "Real-estate work should connect title, contractual rights, project disclosures, approvals, payment history and physical progress. A complaint or agreement review is stronger when the property, unit, project registration and promised obligations are described consistently across every document.",
      "Assistance may cover development documentation, purchaser or promoter disputes, MAHARERA complaints and replies, title review, municipal or MRTP-related documentation and negotiated resolution.",
    ],
    services: [
      { title: "MAHARERA complaints and replies", text: "Build a dated record of registration disclosures, agreement terms, payments, possession commitments, correspondence and the specific relief or defence requiring consideration." },
      { title: "Development documentation", text: "Draft or review development agreements, powers, allocation, consideration, approvals, milestones, default, termination and handover provisions." },
      { title: "Purchaser document review", text: "Compare project registration information, title report, encumbrances, sanctioned plans, allotment material, deviation reports and the proposed agreement for sale." },
      { title: "Due diligence and approvals", text: "Identify title-chain, authority, encumbrance, land-use, municipal, planning and project-document gaps within the agreed scope of review." },
    ],
    matters: ["Project delay, possession and refund-related disputes", "Agreement-for-sale and allotment documentation", "Development agreements and landowner-promoter issues", "Title, encumbrance and authority due diligence", "Municipal, MRTP and approval-document coordination", "Negotiation, conciliation and property mediation"],
    documents: ["MahaRERA registration number and downloaded project disclosures", "Allotment letter, agreement drafts and deviation reports", "Payment receipts, demand letters and account statement", "Title report, property records and encumbrance information", "Sanctioned plans, commencement or occupancy material", "Correspondence, promised dates and site-progress records"],
    process: standardProcess,
    scopeNote: "A MahaRERA registration or portal disclosure is not a substitute for transaction-specific title and contract review. Relief depends on the agreement, statutory framework, evidence, project status and forum. Stamp duty, registration, tax and technical questions may require separate professional input.",
    sources: [{ label: "MahaRERA: official guidance before buying property", href: "https://maharera.maharashtra.gov.in/buying-property" }, { label: "MahaRERA: resources for homebuyers", href: "https://maharera.maharashtra.gov.in/resources-homebuyers" }],
    faqs: [
      { question: "What should a purchaser check before signing?", answer: "Official MahaRERA guidance recommends reviewing project details, title information, encumbrances, approvals, complaints, the uploaded model agreement and any deviation report, as well as ensuring unit, carpet area and possession details are correct." },
      { question: "Can development agreements be reviewed before execution?", answer: "Yes. Early review can address authority, development rights, consideration, allocation, approvals, milestones, default, termination, possession, indemnities, dispute resolution and registration implications." },
      { question: "Is mediation possible in a property dispute?", answer: "It may be, particularly where participants need tailored implementation terms. Suitability, necessary parties, title consequences, registration and independent advice should be considered before final terms are signed." },
    ],
  },
  trusts: {
    path: "/trusts-societies",
    shortTitle: "Trusts & societies",
    eyebrow: "Governance and compliance in Maharashtra",
    title: "Trusts and societies in Maharashtra",
    description: "Governance, change reporting, compliance, drafting and dispute information under the Maharashtra Public Trusts Act and Societies Registration Act.",
    intro: [
      "Public trust and society matters frequently depend on the governing instrument, the current public record, valid meetings, resolutions and timely reporting of changes. Clear institutional records reduce uncertainty when office-bearers change or a dispute arises.",
      "The principal Maharashtra statute is now titled the Maharashtra Public Trusts Act, 1950; older records and commentary may refer to its former Bombay Public Trusts Act title. The Societies Registration Act framework may also apply depending on the entity.",
    ],
    services: [
      { title: "Registration and record changes", text: "Prepare or review instruments, applications, change reports, supporting resolutions and the evidence needed to update the public record." },
      { title: "Governance documents", text: "Review trust deeds, constitutions, by-laws, delegation, meeting procedure, minutes, resolutions and role descriptions." },
      { title: "Compliance systems", text: "Map recurring filings, accounts, audit, registers, approvals and responsibility for maintaining institutional records." },
      { title: "Disputes and inquiries", text: "Organise the governing documents, public record, elections or appointments, resolutions, correspondence and forum-specific relief." },
    ],
    matters: ["Trust or society formation and governing instruments", "Change reports and office-bearer updates", "Meeting, election, resolution and membership disputes", "Property, authority and record-management issues", "Regulatory correspondence, inquiries and responses", "Governance-focused negotiation or mediation"],
    documents: ["Trust deed, constitution, memorandum and by-laws", "Registration certificate and current public record", "Minutes, resolutions, notices and attendance records", "Change reports, inquiry papers and previous orders", "Property records, accounts and audit material where relevant", "A chronology of office-bearers and disputed events"],
    process: standardProcess,
    scopeNote: "Trust and society procedure depends on the entity's instruments, registration history, public record, applicable statute and the relief sought. Tax registration, exemptions, foreign contribution and specialised accounting are distinct workstreams that may require separate advice.",
    faqs: [
      { question: "Is the Bombay Public Trusts Act still the correct name?", answer: "The statute is currently titled the Maharashtra Public Trusts Act, 1950. Older documents may use the former Bombay Public Trusts Act name, so both may appear in historical records." },
      { question: "Why are minutes and resolutions important?", answer: "They help establish notice, quorum, authority, the decision actually taken and responsibility for implementation. Poor records can complicate change reporting, banking, property and internal disputes." },
      { question: "Can governance disputes be mediated?", answer: "Some can, especially where ongoing institutional functioning matters. Statutory duties, necessary participants and any approval or public-record steps must still be respected." },
    ],
  },
  family: {
    path: "/family-law",
    shortTitle: "Family & matrimonial",
    eyebrow: "Family disputes and protective procedure",
    title: "Family and matrimonial matters",
    description: "Information on divorce, custody, visitation, maintenance, domestic-violence proceedings and family mediation in Maharashtra.",
    intro: [
      "Family matters require careful attention to safety, children, finances, jurisdiction, existing orders and the immediate practical arrangements between participants. A documentation-first approach can reduce avoidable conflict and help distinguish urgent protection from issues suitable for negotiation.",
      "Assistance may cover contested or mutual-consent proceedings, custody and visitation, maintenance, domestic-violence remedies, settlement documentation and suitable mediation processes.",
    ],
    services: [
      { title: "Divorce and allied proceedings", text: "Assess jurisdiction, personal-law framework, pleadings, service, interim needs, evidence and whether a consent or contested route is realistically available." },
      { title: "Custody and visitation", text: "Focus on the child's welfare, existing care pattern, schooling, health, safety, communication and workable interim or long-term arrangements." },
      { title: "Maintenance and financial disclosure", text: "Organise income, expenses, dependants, assets, liabilities and existing support so requests or responses are evidence-based." },
      { title: "Protection and settlement", text: "Address domestic-violence remedies, urgent orders, negotiated terms or mediation only where the process is safe, voluntary and appropriate." },
    ],
    matters: ["Contested and mutual-consent divorce", "Child custody, visitation and parenting arrangements", "Interim and final maintenance-related proceedings", "Domestic-violence applications and responses", "Settlement terms, consent documents and implementation", "Family mediation suitability and process planning"],
    documents: ["Marriage and identity records relevant to jurisdiction", "A chronology of separation and current proceedings", "Income, expense, tax, bank and employment material", "Child-related school, health and care information", "Existing notices, complaints, pleadings and orders", "A list of urgent safety, housing or support concerns"],
    process: standardProcess,
    scopeNote: "Safety and free decision-making come first. Mediation is not appropriate for every family matter and should not be used to avoid urgent protective remedies. Child-related arrangements remain subject to welfare considerations and any required court scrutiny.",
    faqs: [
      { question: "Is mediation always required or suitable?", answer: "No. It may be encouraged or useful in some matters, but suitability depends on safety, capacity, voluntariness, urgency, power balance and the issues requiring decision." },
      { question: "What financial documents are usually helpful?", answer: "Income records, tax returns, bank statements, regular expenses, liabilities, dependants and existing support records may be relevant. The necessary period and scope depend on the proceeding." },
      { question: "Can interim relief be requested?", answer: "Depending on facts and law, interim maintenance, custody, visitation, residence, protection or other relief may be considered. The forum and evidence requirements are case-specific." },
    ],
  },
  drafting: {
    path: "/drafting-advisory",
    shortTitle: "Drafting & advisory",
    eyebrow: "Document-led legal work",
    title: "Legal drafting and advisory",
    description: "Pleadings, notices, agreements, due diligence and written legal-opinion information for individuals, businesses and institutions.",
    intro: [
      "Good drafting starts before the first sentence. The purpose, audience, facts, definitions, evidence, desired outcome and implementation risks should be identified first. A document that is concise but incomplete can create more uncertainty than a longer, properly structured one.",
      "Assistance may include fresh drafts, structured review of an existing document, notices and replies, pleadings, transaction documents, due diligence reports and written opinions based on a defined document set.",
    ],
    services: [
      { title: "Pleadings and applications", text: "Develop issue-led pleadings, affidavits, appeals, revisions and applications with a clear chronology, material facts, relief and annexure plan." },
      { title: "Agreements and transaction documents", text: "Translate commercial or family arrangements into obligations, conditions, timelines, payment, default, termination, dispute and implementation provisions." },
      { title: "Notices and replies", text: "Check facts, contractual or statutory basis, admissions, relief, limitation, service and the strategic effect of correspondence before it is sent." },
      { title: "Opinions and due diligence", text: "Define assumptions, sources, legal issues, qualifications, risk levels, missing documents and practical options in a usable written format." },
    ],
    matters: ["Civil and criminal pleadings and procedural applications", "Commercial, property and family agreements", "Demand notices, termination notices and replies", "Title, project, corporate or institutional document review", "Issue-specific legal opinions and risk notes", "Revision of existing drafts and negotiation support"],
    documents: ["Clear instructions and the intended use of the document", "A chronology and list of people or entities involved", "Existing agreements, drafts and related correspondence", "Supporting evidence, public records and approvals", "Commercial terms, payment milestones and decision authority", "Known deadlines, forum rules and counterpart drafts"],
    process: standardProcess,
    scopeNote: "A draft is only as reliable as the instructions and documents on which it is based. Tax, accounting, technical, valuation, registration and foreign-law consequences may need separate professional input. Execution formalities should be checked before signature.",
    faqs: [
      { question: "Can an existing draft be reviewed instead of rewritten?", answer: "Yes. The review scope can be limited to legal risk, consistency, enforceability, negotiation points, formatting or a complete revision, depending on the document and objective." },
      { question: "What makes a useful written legal opinion?", answer: "It should identify the question, material facts, documents reviewed, assumptions, applicable law, analysis, qualifications, practical options and information still needed." },
      { question: "Can urgent drafting be requested?", answer: "Urgency can be assessed after reviewing scope, documents and deadline. A realistic turnaround should preserve enough time for factual verification and client review." },
    ],
  },
  baramati: {
    path: "/baramati-lawyer",
    shortTitle: "Baramati office",
    eyebrow: "Office in Baramati, Pune district",
    title: "Advocate and mediator in Baramati",
    description: "Office and consultation information for civil, criminal, property, family, trust, drafting and mediation matters from Baramati.",
    intro: [
      "The office is located at Shop No. 14, Vardhaman Capital, Suryanagari, Baramati. Consultations are by appointment so that the matter, immediate deadline and document requirements can be identified before a substantive meeting.",
      "Work includes civil and criminal litigation, property and MAHARERA matters, trusts and societies, family matters, drafting, advisory and neutral mediation. Forum and travel requirements are assessed for each matter rather than assumed from the client's location alone.",
    ],
    services: [
      { title: "Local consultation and document review", text: "Arrange an appointment with a short chronology and indexed documents so the first discussion can focus on jurisdiction, relief and next steps." },
      { title: "Court and tribunal matters", text: "Assess the correct forum, stage, limitation and appearance requirements for matters in Baramati, Pune district or elsewhere in Maharashtra." },
      { title: "Property and institutional work", text: "Review property, development, trust, society and business records with the relevant registration or regulatory context." },
      { title: "Mediation and online meetings", text: "Screen suitable disputes for a neutral process in person or online, with separate appointment and conflict safeguards." },
    ],
    matters: ["Civil, property, tenancy and recovery disputes", "Criminal matters, bail and procedural applications", "Development, MAHARERA and documentation", "Family, trust and society matters", "Notices, agreements, opinions and due diligence", "Mediation suitability and appointment enquiries"],
    documents: ["A one-page chronology and immediate deadline", "Notices, summons, pleadings or orders already received", "The key agreement, title record or complaint", "Payment, identity and authority records relevant to the matter", "A list of all adverse and related parties for conflict checking", "Preferred consultation language: English, Marathi or Hindi"],
    process: standardProcess,
    scopeNote: "Office location does not determine jurisdiction or whether a matter can be accepted. Acceptance follows identity and conflict checks, scope assessment and written terms where required. Mediation appointments are neutral and separate from representation.",
    faqs: [
      { question: "Where is the Baramati office?", answer: "Shop No. 14, Vardhaman Capital, Suryanagari, Baramati - 413133, District Pune. Meetings are by prior appointment." },
      { question: "Are consultations available in Marathi?", answer: "Consultations may be conducted in English, Marathi or Hindi, subject to appointment and the needs of the matter." },
      { question: "Can a Baramati matter require another forum?", answer: "Yes. Jurisdiction depends on subject matter, location of events or property, parties, statutory forum and procedural stage. It should be checked from the documents." },
    ],
  },
  pune: {
    path: "/pune-lawyer",
    shortTitle: "Pune matters",
    eyebrow: "Pune district and Maharashtra forums",
    title: "Legal matters in Pune and across Maharashtra",
    description: "Consultation and appearance information for civil, criminal, property, family, trust, drafting and mediation matters connected with Pune.",
    intro: [
      "Pune matters may arise before civil and criminal courts, the Family Court, consumer or co-operative forums, MAHARERA, tribunals or the Bombay High Court. The correct forum depends on the statute, territory, relief and stage rather than a general city label.",
      "Initial review can be conducted by appointment with digital documents where appropriate. Appearance, filing, local coordination and travel requirements are then planned for the particular forum and deadline.",
    ],
    services: [
      { title: "Forum and jurisdiction assessment", text: "Identify the court, tribunal or authority, territorial basis, filing stage, limitation and any immediate procedural requirement." },
      { title: "Litigation and hearings", text: "Prepare pleadings, applications, document sets and hearing strategy for accepted civil, criminal and related matters." },
      { title: "Property and MAHARERA", text: "Assess project records, development documents, title material, complaints, replies and negotiated or mediated resolution options." },
      { title: "Remote consultation and mediation", text: "Use online meetings for focused intake or suitable neutral mediation when participant location and confidentiality arrangements permit." },
    ],
    matters: ["Civil, property, commercial and recovery proceedings", "Criminal matters, bail, revisions and quashing assessment", "MAHARERA and development documentation", "Family, trust and society disputes", "Agreements, notices, opinions and due diligence", "Online or in-person mediation for suitable disputes"],
    documents: ["Case number, court or authority and next date", "A chronology and list of parties", "Key contracts, title documents or project records", "Existing pleadings, orders, notices and correspondence", "Payment records and supporting evidence", "Any limitation, possession, custody or arrest-related urgency"],
    process: standardProcess,
    scopeNote: "A Pune connection does not by itself establish the correct court or authority. Jurisdiction, maintainability, limitation, local filing requirements and whether the matter can be accepted are assessed after reviewing the facts and documents.",
    faqs: [
      { question: "Can the first consultation be online?", answer: "Yes, by appointment where the matter is suitable for remote review. A short outline and indexed documents help make the meeting efficient." },
      { question: "Do you appear in Pune and the Bombay High Court?", answer: "Appearances may include Pune forums and the Bombay High Court, subject to the matter, forum, stage, acceptance and practical arrangements." },
      { question: "Can a Pune property dispute be mediated?", answer: "Some property disputes are suitable, particularly where participants need tailored implementation terms. Necessary parties, title, registration, statutory approvals and independent advice must still be considered." },
    ],
  },
};
